# Generated by Django 2.2 on 2019-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('data', models.FileField(upload_to='')),
                ('img_src', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
