# Generated by Django 2.2 on 2019-04-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfile',
            old_name='data',
            new_name='file_field',
        ),
        migrations.RenameField(
            model_name='testfile',
            old_name='name',
            new_name='file_name',
        ),
    ]
