# Generated by Django 2.2 on 2019-04-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0002_auto_20190424_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestFile',
            new_name='CloudFile',
        ),
    ]
