# Generated by Django 2.2 on 2019-04-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0003_auto_20190424_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudFileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_storage.CloudFileCategory'),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='tags',
            field=models.ManyToManyField(to='cloud_storage.CloudFileTag'),
        ),
    ]
