# Generated by Django 2.2 on 2019-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0004_auto_20190424_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='cloudfile',
            unique_together={('file_name', 'category')},
        ),
    ]
