# Generated by Django 2.2 on 2019-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0006_auto_20190424_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_name',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cloudfile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cloudfile',
            name='category',
        ),
    ]
