# Generated by Django 2.2 on 2019-04-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0007_auto_20190424_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='category',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_storage.CloudFileCategory'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='cloud_storage.CloudFileTag'),
        ),
    ]
