# Generated by Django 2.2 on 2019-04-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0008_auto_20190424_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_storage.CloudFileCategory'),
        ),
    ]
