# Generated by Django 2.2 on 2019-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0009_auto_20190424_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfile',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='file_field',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
