# Generated by Django 2.2 on 2019-04-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0010_auto_20190424_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudfile',
            old_name='img_src',
            new_name='gcloud_img_src',
        ),
    ]
