# Generated by Django 2.2.5 on 2019-11-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowsheet_landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
