# Generated by Django 2.2.5 on 2019-11-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_storage', '0011_auto_20190424_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('brand_icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_icon', to='cloud_storage.CloudFile')),
            ],
        ),
    ]
