# Generated by Django 2.2.5 on 2019-11-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0011_auto_20190424_1453'),
        ('affiliate_marketing', '0002_auto_20191104_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedAccordian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='affiliate_marketing.Brand')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_accoridan_image', to='cloud_storage.CloudFile')),
            ],
        ),
    ]
