# Generated by Django 2.2.5 on 2019-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0003_featuredaccordian'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='homepage_url',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
