# Generated by Django 2.2.5 on 2019-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0004_brand_homepage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredaccordian',
            name='feature_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
