# Generated by Django 2.2.5 on 2019-11-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0006_brandslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
