# Generated by Django 2.2.5 on 2019-11-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0007_brand_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandslider',
            name='headline',
        ),
    ]
