# Generated by Django 2.2.5 on 2019-11-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0008_remove_brandslider_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='affiliate_marketing.Brand')),
            ],
        ),
    ]
