# Generated by Django 2.2.5 on 2019-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0009_trustedbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='vendor_code',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
