# Generated by Django 2.2.5 on 2019-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0010_brand_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='storefront_category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
