# Generated by Django 2.2.5 on 2019-11-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0011_brand_storefront_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandslider',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
