# Generated by Django 2.2.5 on 2019-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0012_brandslider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandslider',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Brand Name'),
        ),
        migrations.AlterUniqueTogether(
            name='brandslider',
            unique_together={('name', 'brand')},
        ),
    ]
