# Generated by Django 2.2.5 on 2019-11-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0013_auto_20191106_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandslider',
            name='button_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brandslider',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
    ]
