# Generated by Django 2.2.5 on 2019-11-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0014_auto_20191106_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandslider',
            name='homepage_button_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandslider',
            name='shop_button_active',
            field=models.BooleanField(default=True),
        ),
    ]
