# Generated by Django 2.2.5 on 2019-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0015_auto_20191106_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='feature_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brandslider',
            name='button_active',
            field=models.BooleanField(default=True, verbose_name='Show Custom Button'),
        ),
        migrations.AlterField(
            model_name='brandslider',
            name='homepage_button_active',
            field=models.BooleanField(default=True, verbose_name='Show Homepage Link'),
        ),
        migrations.AlterField(
            model_name='brandslider',
            name='shop_button_active',
            field=models.BooleanField(default=True, verbose_name='Show Shop Link'),
        ),
    ]
