# Generated by Django 2.2.5 on 2019-11-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0016_auto_20191106_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredaccordian',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Accoridion Enabled'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='feature_active',
            field=models.BooleanField(default=True, verbose_name='Brand Enabled'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Brand Priority'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='storefront_category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Storefront Category'),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Brand Category'),
        ),
        migrations.AlterField(
            model_name='brandslider',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Slider Enabled'),
        ),
        migrations.AlterField(
            model_name='brandslider',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Slider Priority'),
        ),
    ]
