# Generated by Django 2.2.5 on 2019-11-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0017_auto_20191106_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='trusted_active',
            field=models.BooleanField(default=True, verbose_name='Trusted Brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='trusted_priority',
            field=models.IntegerField(default=0, verbose_name='Trusted Brand Priority'),
        ),
    ]
