# Generated by Django 2.2.5 on 2019-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0018_auto_20191106_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredaccordian',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
