# Generated by Django 2.2.5 on 2019-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0019_featuredaccordian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brandslider',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Slider Enabled'),
        ),
    ]
