# Generated by Django 2.2.5 on 2019-11-15 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_marketing', '0020_auto_20191107_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandslider',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='brandslider',
            name='last_changed_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
