# Generated by Django 2.2 on 2019-05-08 05:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_storage', '0011_auto_20190424_1453'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('period', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('yearly', 'yearly')], default='monthly', max_length=32)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_changed_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('for_sale', models.BooleanField(default=True, verbose_name='for_sale')),
                ('discontinued', models.BooleanField(default=True, verbose_name='discontinued')),
                ('vendor', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('upc', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('vendor_code', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('man_part_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('htc_number', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('text_document', models.TextField(blank=True, null=True)),
                ('spec_kv', models.TextField(blank=True, null=True)),
                ('details_kv', models.TextField(blank=True, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('uofm', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('inventory', models.IntegerField(default=0)),
                ('bin_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date created')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_changed_timestamp', models.DateTimeField(auto_now=True)),
                ('job_timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ManyToManyField(blank=True, default=None, null=True, to='cloud_storage.CloudFile')),
                ('parent_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPromotionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_changed_timestamp', models.DateTimeField(auto_now=True)),
                ('job_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_changed_timestamp', models.DateTimeField(auto_now=True)),
                ('job_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='End Date')),
                ('promo_code', models.CharField(blank=True, default=None, max_length=32, null=True, unique=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('discount', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_changed_timestamp', models.DateTimeField(auto_now=True)),
                ('job_timestamp', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.ProductPromotionCategory')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.Product')),
                ('tags', models.ManyToManyField(blank=True, default=None, null=True, to='storefront.ProductTag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='storefront.ProductTag'),
        ),
        migrations.CreateModel(
            name='EmployeeProductQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_due', models.DateTimeField(blank=True, default=None, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('rating_one', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('rating_two', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.Product')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='User Membership Start Date')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='User Membership End Date')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_changed_timestamp', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.MembershipPlan')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
