# Generated by Django 2.2.5 on 2019-11-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='carousel_name',
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='carousel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storefront.Carousel'),
        ),
    ]
